staging-installcheck: fix syntax failure introduced with 597d48be
TypeError: InstallChecker.upload_failure() takes 3 positional arguments but 4 were given
(devel was used in a prototype, but later reworked)