devel-project: Add a func callback to main parser
Workarouds https://bugs.python.org/issue16308
Which otherwise causes:
  AttributeError: 'Namespace' object has no attribute 'func'