check_source: fix crash AttributeError: 'CheckSource' object has no attribute 'review_message'
An old typo, that was introduced in an attempt to support scm synced PRs