rabbit-openqa: encode the product version in job name
The bot in the SUSE side crashed recently [0] due to a
name collision:

    File "/godata/pipelines/SUSE.openQA/./scripts/gocd/rabbit-openqa.py", line 284, in check_some_projects
      project.update_staging_status(staging)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
    File "/godata/pipelines/SUSE.openQA/./scripts/gocd/rabbit-openqa.py", line 175, in update_staging_status
      raise Exception(f'Names of job #{id} and #{taken_names[name]} collide: {name}')
  Exception: Names of job #17092411 and #16972018 collide: Default-qcow-Updates-Staging-install_ltp+sle-micro+Default-qcow-Updates-Staging@aarch64

This is a bit of a niche situation, as the project is in the
SUSE:SLFO:Kernel:1.0 project, where we share the kernel between SLFO 1.0
and 1.1.

This means that the same tests are run against both Micro 6.0 and Micro
6.1, and might thus collide.

[0] https://botmaster.suse.de/go/tab/build/detail/SUSE.openQA/69498/Run/1/Run

Signed-off-by: Eugenio Paolantonio <eugenio.paolantonio@suse.com>